Import( 'env', 'libs', 'installdir', )

mylibs = libs + [ 'gtest', 'gmock', 'pthread' ]

myenv = env.Clone()

myenv.Append(CPPPATH='.')

sources = """
    cppshouldtest.cpp
    should.cpp
    shouldbe.cpp
    expectations/contains.cpp
    expectations/be.cpp
    """.split()

output = myenv.Program(
    'cppshouldtest',
    source=sources,
    LIBS=mylibs
    )

installoutput = myenv.Install( installdir, output )

env.Alias( 'test', installoutput )
