Import( 'env', 'libs', 'installdir', )

mylibs = libs + [ 'gtest', 'pthread' ]

sources = """
    cppshouldtest.cpp
    expectations/contains.cpp
    """.split()

output = env.Program( 'cppshouldtest', source = sources, LIBS=mylibs )

installoutput = env.Install( installdir, output )

env.Alias( 'test', installoutput )
